### ISSUE TITLE
currentPackage()、currentActivity()输出为空 

### ISSUE THREAD

**Issue by caiabc** [TonyJiangWJ/Auto.js#10]
使用修改版.armeabi-v7a.20240417 和 修改版.armeabi-v7a.20240914
脚本中，
log("当前程序页面：",currentPackage(),currentActivity())
均为空。

查阅了 老的issue，
https://github.com/TonyJiangWJ/Auto.js/issues/2

TonyJiangWJ commented on Apr 18
已修复版本：4.1.24.0417

可是，我已经是0417版本了，怎么还是无法获得currentPackage(),currentActivity()呢？

如果是用修改版.armeabi-v7a.20240311，能获得currentPackage(),currentActivity()，就是经常不正确，也不明白。

麻烦您抽空帮看看？谢谢！

**Comment by caiabc** [comment]
补充，多试几次，能获得结果了，但是，和0311版本一样了，结果不正确，是一个旧的不更新到最新的app和页面。

**Comment by caiabc** [comment]
又重新测试了好几回，貌似会更新了，先close继续观察。

**Comment by TonyJiangWJ** [comment]
不准确是对的 它基于无障碍事件读取的记录本身就是不准的 之前几个版本获取不到是不小心改错了点东西。
你可以自己编写代码重新获取具体可以参考 https://github.com/TonyJiangWJ/AutoScriptBase/blob/master/lib/BaseCommonFunctions.js#L156

**Comment by caiabc** [comment]
感谢您的关注和回复。
经过一段时间的观察，现在能够获得正确的,currentPackage(),currentActivity()了，
只不过，必须多获取几次，才能确保成功获得准确的结果，如果只是获取一两次，则还是获得老的页面。
我用的是这样的循环，就可以了。
    for(var i = 0; i < 20; i++){
        log(currentActivity())
        sleep(500)
        if (currentActivity()=="com.kankunit.smartknorns.MainActivity")
            break;
    }
