### ISSUE TITLE
加载脚本目录异常问题

### ISSUE THREAD

**Issue by llm3824** [TonyJiangWJ/Auto.js#11]
MI10 MIUI13稳定版安装[AutoJS Modify]最新版后，刷新页面能够加载脚本目录，但是目录里JS等文件无法加载识别。MI6 MIUI13开发版安装[AutoJS Modify]最新版后，刷新页面无法加载脚本内目录，autojs 页面添加新文件/文件夹提示创建失败。大佬分析下是什么原因呢

**Comment by TonyJiangWJ** [comment]
安卓10及以上需要授权全部文件的管理权限 你估计在第一次打开后没有进行授权 关闭重新打开或者重新安装触发授权

**Comment by llm3824** [comment]
稳定版确实是忽略了首次打开没授权，开发版可能因为授权不同，暂时没有解决，我自己先研究下了
