### ISSUE TITLE
报错: { [JavaException: java.lang.IllegalStateException: Image is already closed] fileName: '<init>', lineNumber: 30 }

### ISSUE THREAD

**Issue by agandab** [TonyJiangWJ/Auto.js#14]
报错如下:
{ [JavaException: java.lang.IllegalStateException: Image is already closed] fileName: '<init>', lineNumber: 30 }

点解？代码在autoX正常运行。在auto M 0322 运行第一次正常,第二次后易报错。

**Comment by TonyJiangWJ** [comment]
不给代码只给报错信息 我怀疑你在耍流氓

**Comment by agandab** [comment]
有可能跟 截屏+找色+剪切+二值化 一系列图片处理动作 过于频繁有关，改进代码之后就没问题了。
