### ISSUE TITLE
大佬，请教个问题

### ISSUE THREAD

**Issue by twinklelucas** [TonyJiangWJ/Auto.js#16]
为啥我编译完，app可以安装一切都正常，但是OCR结果一直是空的，model加载也是失败，是不是编译漏了什么命令，有空答复一下，没空就算了^_^

**Comment by TonyJiangWJ** [comment]
什么设备 可能设备不支持？ 你可以安装我编译的试试能不能识别

**Comment by twinklelucas** [comment]
> 什么设备 可能设备不支持？ 你可以安装我编译的试试能不能识别

你编译的就可以啊，好奇怪，手机的log显示这个：...e-Lite/lite/model_parser/model_parser.cc:882 LoadModelFbsFromFile] 
    warning: the version of opt that transformed this model is not consistent with current Paddle-Lite version.
          version of opt:6010b5f
          version of current Paddle-Lite:6010b5f0

**Comment by LZX284** [comment]
> > 什么设备 可能设备不支持？ 你可以安装我编译的试试能不能识别
> 
> 你编译的就可以啊，好奇怪，手机的log显示这个：...e-Lite/lite/model_parser/model_parser.cc:882 LoadModelFbsFromFile] warning: the version of opt that transformed this model is not consistent with current Paddle-Lite version. version of opt:6010b5f version of current Paddle-Lite:6010b5f0

我也遇到过这个错误提示，不过不影响OCR使用。另外，冒昧问一下，@TonyJiangWJ ，大佬的autojs确实不错，但现版本的编译难度较大，OCR编译的相关配置较麻烦，不知道是否允许改进一下？如果大佬没空那不知道我能不能提交一个PR给大佬看看行不行？
附：[PaddleOCR4Android](https://github.com/LZX284/PaddleOCR4Android)（这是个人根据大佬们的改进结果制作的一个OCR示例 ）

**Comment by twinklelucas** [comment]
> > > 什么设备 可能设备不支持？ 你可以安装我编译的试试能不能识别
> > 
> > 
> > 你编译的就可以啊，好奇怪，手机的log显示这个：...e-Lite/lite/model_parser/model_parser.cc:882 LoadModelFbsFromFile] warning: the version of opt that transformed this model is not consistent with current Paddle-Lite version. version of opt:6010b5f version of current Paddle-Lite:6010b5f0
> 
> 我也遇到过这个错误提示，不过不影响OCR使用。另外，冒昧问一下，@TonyJiangWJ ，大佬的autojs确实不错，但现版本的编译难度较大，OCR编译的相关配置较麻烦，不知道是否允许改进一下？如果大佬没空那不知道我能不能提交一个PR给大佬看看行不行？ 附：[PaddleOCR4Android](https://github.com/LZX284/PaddleOCR4Android)（这是个人根据大佬们的改进结果制作的一个OCR示例 ）

老哥你怎么弄的，方便加个QQ吗，我OCR出来都是空的，不知道是不是编译错了

**Comment by twinklelucas** [comment]
> > 老哥你怎么弄的，方便加个QQ吗，我OCR出来都是空的，不知道是不是编译错了
> 
> 那个，几年前Q号被封后就没再用过了……OCR识别结果为空，我的经验是，只要paddle加载label和model成功，一般识别结果就不会为空，有几次结果为空，加断点打印log都是显示label或model加载失败，你可以先检查一下标签和模型路径以及加载过程是否正常

我自己编译的版本，每次都是空，用大佬编译的就没问题

**Comment by LZX284** [comment]
> 我自己编译的版本，每次都是空，用大佬编译的就没问题

一般标签加载失败 识别结果会变成XX，模型加载失败结果为空或报错，不过都只是偶尔出现，你这每次都空的可能是Paddle自身或依赖库编译出错了。大佬的源码编译时需要下载一大堆依赖，但自己没有好的梯子，经常下载过慢或是下载文件出错导致编译不了，所以我就做了一个把下载好的依赖放进源码的一个版本，这样编译成功率就高了不少

**Comment by twinklelucas** [comment]
> > 我自己编译的版本，每次都是空，用大佬编译的就没问题
> 
> 一般标签加载失败 识别结果会变成XX，模型加载失败结果为空或报错，不过都只是偶尔出现，你这每次都空的可能是Paddle自身或依赖库编译出错了。大佬的源码编译时需要下载一大堆依赖，但自己没有好的梯子，经常下载过慢或是下载文件出错导致编译不了，所以我就做了一个把下载好的依赖放进源码的一个版本，这样编译成功率就高了不少

好的，下一步我试试用梯子搞一下，github有个免费的梯子freefq，你可以试试

**Comment by LZX284** [comment]
@twinklelucas  找到错误原因了！
这是根据个人经验优化编译配置后的版本（其他都没有改动）：[Auto.jsM 编译配置优化版](https://github.com/LZX284/Auto.js)
用大佬最新版源码编译后也出现了和你同样的问题，而且log中提示了多个类似 “第5次 校验是否初始化成功: false”的信息，说明加载检验5次都是false，模型加载失败，识别结果就只能为空，具体原因不明，不知道大佬能不能帮忙看看 @TonyJiangWJ

**Comment by twinklelucas** [comment]
> 

多谢，你也是大佬，小弟是业余的

**Comment by twinklelucas** [comment]
> @twinklelucas 找到错误原因了！ 这是根据个人经验优化编译配置后的版本（其他都没有改动）：[Auto.jsM 编译配置优化版](https://github.com/LZX284/Auto.js) 用大佬最新版源码编译后也出现了和你同样的问题，而且log中提示了多个类似 “第5次 校验是否初始化成功: false”的信息，说明加载检验5次都是false，模型加载失败，识别结果就只能为空，具体原因不明，不知道大佬能不能帮忙看看 @TonyJiangWJ

多谢，你也是大佬，小弟是业余的

**Comment by twinklelucas** [comment]
> @twinklelucas 找到错误原因了！ 这是根据个人经验优化编译配置后的版本（其他都没有改动）：[Auto.jsM 编译配置优化版](https://github.com/LZX284/Auto.js) 用大佬最新版源码编译后也出现了和你同样的问题，而且log中提示了多个类似 “第5次 校验是否初始化成功: false”的信息，说明加载检验5次都是false，模型加载失败，识别结果就只能为空，具体原因不明，不知道大佬能不能帮忙看看 @TonyJiangWJ

老哥你能不能把新版本的paddle ocr整合进去看看效果有没有好一点？现在的版本识别正确率还是不太满意

**Comment by LZX284** [comment]
> 老哥你能不能把新版本的paddle ocr整合进去看看效果有没有好一点？现在的版本识别正确率还是不太满意

新版是2.5版的吧？效果应该更好了，但不知道要整合到哪里？大佬的autojs我编译的也有问题，目前还没找到解决办法

**Comment by twinklelucas** [comment]
> > 老哥你能不能把新版本的paddle ocr整合进去看看效果有没有好一点？现在的版本识别正确率还是不太满意
> 
> 新版是2.5版的吧？效果应该更好了，但不知道要整合到哪里？大佬的autojs我编译的也有问题，目前还没找到解决办法

有时间用autoxjs摸索下，这个我编译完是可以用的

**Comment by LZX284** [comment]
> 有时间用autoxjs摸索下，这个我编译完是可以用的

autox的话，6.X目前不太稳定，5.X对新设备的兼容性不足，一些新功能加入就容易出问题，可能的话倒是希望 @TonyJiangWJ 大佬能出手，这样就算自己编译不了直接用大佬编译好的也行

**Comment by LZX284** [comment]
> 我自己编译的版本，每次都是空，用大佬编译的就没问题

@twinklelucas  @TonyJiangWJ  能正常显示OCR结果了……发现了一些导致异常的语句，但这些语句看起来很正常，log显示的结果却匪夷所思，可能只是我自己不理解吧，毕竟我自己也不是专业的，只是摸索的经验多了一些而已……

问题应该是出在[Predictor.java](https://github.com/TonyJiangWJ/Auto.js/blob/main/autojs-aar/paddleocr/src/main/java/com/baidu/paddle/lite/ocr/Predictor.java) 这个类的一个方法checkModelLoadedSuccess上：

```
    public boolean init(Context appCtx, String modelPath, String labelPath) {
        isLoaded = loadModel(appCtx, modelPath, cpuThreadNum, cpuPowerMode);
        if (!isLoaded) {
            return false;
        }
        isLoaded = loadLabel(appCtx, labelPath);
        if (!checkModelLoadedSuccess()) {
            init(appCtx, modelPath, labelPath);
        }
        return isLoaded;
    }

    /**
     * 初始化模型后通过识别预设图片校验是否初始化成功
     * 曲线救国 深层的失败原因需要后续排查
     *
     * @return
     */
    private boolean checkModelLoadedSuccess() {
        if (!isLoaded) {
            return false;
        }
        List<OcrResult> results = runOcr(checkingBitmap);
        StringBuilder sb = new StringBuilder();
        for (OcrResult result : results) {
            sb.append(result.getLabel());
        }
        isLoaded = "测试".equals(sb.toString());
        Log.d(TAG, "第" + retryTime + "次 校验是否初始化成功: " + isLoaded);
        return isLoaded || retryTime++ >= 5;
    }
```
原因不知道，反正注释掉图片校验相关的语句后，ocr结果反而正常了……

**Comment by LZX284** [comment]
@twinklelucas  这个bug太奇怪了，不知道以上的解决方法是否具有通用性，不知道你能不能照我提到的方法改一下，看看编译出来的应用OCR结果是否还都为空？

**Comment by twinklelucas** [comment]
> @twinklelucas 这个bug太奇怪了，以上的解决方法可能不具有通用性，不知道你能不能照我提到的方法改一下，看看编译出来的应用OCR结果是否还都为空？

好的 我明天试试回复你

**Comment by twinklelucas** [comment]
> @twinklelucas 这个bug太奇怪了，以上的解决方法可能不具有通用性，不知道你能不能照我提到的方法改一下，看看编译出来的应用OCR结果是否还都为空？

老哥，我把那段代码注释掉识别结果不为空了，但是每个字符后面都跟着一个\r

**Comment by twinklelucas** [comment]
> @twinklelucas 这个bug太奇怪了，以上的解决方法可能不具有通用性，不知道你能不能照我提到的方法改一下，看看编译出来的应用OCR结果是否还都为空？

老哥，我把那段代码注释掉识别结果不为空了，但是每个字符后面都跟着一个\r

**Comment by LZX284** [comment]
> 老哥，我把那段代码注释掉识别结果不为空了，但是每个字符后面都跟着一个\r

原版的paddleOCR识别结果就是这样的，autojs里面没带\r是另外做了优化，这个bug大概会影响到修改识别结果的相关操作，\r 这类换行符可以自己在源码里加个替换语句删除掉

**Comment by twinklelucas** [comment]
> > 老哥，我把那段代码注释掉识别结果不为空了，但是每个字符后面都跟着一个\r
> 
> 原版的paddleOCR识别结果就是这样的，autojs里面没带\r是另外做了优化，这个bug大概会影响到修改识别结果的相关操作，\r 这类换行符可以自己在源码里加个替换语句删除掉

这段代码不应该有这bug啊，看着就是测试加载不成功的话，重新加载多次而已

**Comment by twinklelucas** [comment]
> > 老哥，我把那段代码注释掉识别结果不为空了，但是每个字符后面都跟着一个\r
> 
> 原版的paddleOCR识别结果就是这样的，autojs里面没带\r是另外做了优化，这个bug大概会影响到修改识别结果的相关操作，\r 这类换行符可以自己在源码里加个替换语句删除掉

问题原因我搞清楚了，大佬这段代码目的是通过checkModelLoadedSuccess这个方法判断识别结果是否和预设的一样，但是识别出来后面带了\r，这会导致判断为加载失败，isLoaded这个属性就为false，而runOcr这个方法一旦isLoaded是false，识别结果就返回空，问题还是出在于paddle的识别结果带了\r

**Comment by LZX284** [comment]
> 问题原因我搞清楚了，大佬这段代码目的是通过checkModelLoadedSuccess这个方法判断识别结果是否和预设的一样，但是识别出来后面带了\r，这会导致判断为加载失败，isLoaded这个属性就为false，而runOcr这个方法一旦isLoaded是false，识别结果就返回空，问题还是出在于paddle的识别结果带了\r

厉害。确实有这个可能。可以写一个补丁验证一下，比如让初步的识别结果除去所有的 \r 再进行判断，看最终的识别结果还会不会出错？

**Comment by twinklelucas** [comment]
> > 问题原因我搞清楚了，大佬这段代码目的是通过checkModelLoadedSuccess这个方法判断识别结果是否和预设的一样，但是识别出来后面带了\r，这会导致判断为加载失败，isLoaded这个属性就为false，而runOcr这个方法一旦isLoaded是false，识别结果就返回空，问题还是出在于paddle的识别结果带了\r
> 
> 厉害。确实有这个可能。可以写一个补丁验证一下，比如让初步的识别结果除去所有的 \r 再进行判断，看最终的识别结果还会不会出错？

老哥比较厉害 我是顺水推舟

**Comment by minirain2000** [comment]
> @twinklelucas 这是根据个人经验优化编译配置后的版本（其他都没有改动）：[Auto.jsM 编译配置优化版](https://github.com/LZX284/Auto.js) 用大佬最新版源码编译后也出现了和你同样的问题，而且log中提示了所有类似 “第5次 校验是否初始化成功: ”的信息结果都是“false”，深层原因不明，不知道大佬能不能帮忙看看 @TonyJiangWJ
[Auto.jsM 编译配置优化版](https://github.com/LZX284/Auto.js)该链接已失效，无法打开网页404

**Comment by LZX284** [comment]
> > [Auto.jsM 编译配置优化版](https://github.com/LZX284/Auto.js)该链接已失效，无法打开网页404

@minirain2000  大佬没回复，也没什么人关注，就删除了。里面主要是注释掉了代理和OCR下载相关的语句，并放入预先下载好的依赖文件作为代替。不过你不是能编译出来吗？

**Comment by LZX284** [comment]
> > [Auto.jsM 编译配置优化版](https://github.com/LZX284/Auto.js-M)该链接已失效，无法打开网页404

@minirain2000  @twinklelucas 
[Auto.js-M](https://github.com/LZX284/Auto.js-M) 补上了链接， 除了优化编译设置，还尝试修复OCR失效的问题，帮忙看看效果怎样？
