### ISSUE TITLE
升级PaddleOCR v3 了吗，大佬牛逼

### ISSUE THREAD

**Issue by LZX284** [TonyJiangWJ/Auto.js#18]
先感谢一下大佬 @TonyJiangWJ  ，这次OCR升级识别效果应该提高了不少

**Comment by TonyJiangWJ** [comment]
没做深度测试 感觉效果差别不大

**Comment by LZX284** [comment]
> 没做深度测试 感觉效果差别不大

官方说是中文提升5%，用默认模型的话感觉不是很明显，但如果能自己优化模型的话，特定场景下的效果应该会好很多。
另外，在适配新版系统时发现了不少问题，不知道大佬的项目需不需要这些改进？大佬可以随意引用这边改进的代码，或是大佬没空的话这边也可以提交一个PR让大佬审核（毕竟这边也引用了大佬不少代码，还是应该感谢大佬啊）

**Comment by TonyJiangWJ** [comment]
你提pr吧 不过我可能审核很慢 也可能直接拒绝 不能接受的话就单单玩AutoX吧，引用这边代码写明来源就行。另外前两个提交pr的人都销号跑路了，体验很不好，不知道为什么。想让修改也没法搞 比如TTS就是烂尾了

**Comment by LZX284** [comment]
> 你提pr吧 不过我可能审核很慢 也可能直接拒绝 不能接受的话就单单玩AutoX吧，引用这边代码写明来源就行。另外前两个提交pr的人都销号跑路了，体验很不好，不知道为什么。想让修改也没法搞 比如TTS就是烂尾了

大概是大佬这边提PR通过的难度比较高吧？而且auto.js原作者的协议限制比较大，用户们又大多是想白嫖的，老是干费力不讨好的事情当然谁也受不了……
提交PR的话，这边也不知道大佬想要哪些代码，要不这样，也无所谓出处什么的，大佬需要的话可以先复制过去，不满意的直接改就行，要是还有什么需要讨论的，大佬说一声，需要的话再提PR，不知道这样行不行？

**Comment by TonyJiangWJ** [comment]
那不用了 我以为你有什么需要改进的东西需要提交 这个项目主要提供给我蚂蚁森林脚本和自用的，主要针对用户而非开发者，我只修改我自己用的时候所遇到的问题。
但是搬运我的代码还是请注明出处，好比我这次升级花了不少时间各种查问题，然后你或者其他人直接全盘复制到别的项目，然后再在他那边附加新的协议，搞得像是出处是他们那边的了。

**Comment by LZX284** [comment]
> 那不用了 我以为你有什么需要改进的东西需要提交 这个项目主要提供给我蚂蚁森林脚本和自用的，主要针对用户而非开发者，我只修改我自己用的时候所遇到的问题。 但是搬运我的代码还是请注明出处，好比我这次升级花了不少时间各种查问题，然后你或者其他人直接全盘复制到别的项目，然后再在他那边附加新的协议，搞得像是出处是他们那边的了。

有关大佬项目的改进也有一些，只是以大佬的能力应该也用不着别人帮忙吧。原作者的协议其实也限制了auto.js的用途，比如，如果将其用在淘宝、京东等日常的一些活动上，并因此获得比正常水平更高的返利或优惠的话，其实这也算是获得一定经济上的利益吧，虽然不是直接搞黑灰产，但严格来说也是违反了不得用于任何商业和盈利用途的规定（后续PRO版也禁用了在这些应用上的使用）。有的人可能无所谓，但不过同为开发者这样用起来感觉也不太舒服，反正也不是不可替代，感觉也就没必要继续在这个项目上折腾了。

**Comment by TonyJiangWJ** [comment]
我觉得你怕不是对商业用途有误解 随便了 非要扯这些永远也扯不完

**Comment by LZX284** [comment]
> 我觉得你怕不是对商业用途有误解 随便了 非要扯这些永远也扯不完

以前曾经有过这样的困惑。不过细想之下，个人感觉原作者的协议也有一些问题，比如具体限制的用途缺乏解释，而且用词也过于绝对。即使是作者，在开源协议上也不能任意规定吧？至少要把范围说清楚，但这么多年也不见原作者有补充说明。而且，有一些关键问题原作者也没有提到的，比如auto.js开发的脚本是否也需要遵循auto.js的协议？按照惯例，linux 上运行的软件明确是不需要受GPL2协议限制的，但auto.js的脚本就没有相关规定可供参考。

**Comment by LZX284** [comment]
@TonyJiangWJ  大佬，这边OCR使用时发现一个问题，如果使用Java API方式识别，得到的结果是没有经过排序的。比如，识别百度示例里的第一张图片，得到的结果是“最终相遇 约定”，而使用封装过的API进行识别则没有这个问题。

**Comment by TonyJiangWJ** [comment]
就是给你自己自定义啊

**Comment by LZX284** [comment]
> 就是给你自己自定义啊

就是排序的方法需要自己自定义吗？使用Java API方式能够自定义的功能更多，但排序一般默认的就够用了吧？需要其它排序方式的情况应该较少，或许可以把默认排序方法也放到 Predictor  这个类里，需要时直接调用，不需要自己再写一遍

**Comment by TonyJiangWJ** [comment]
最基础的API哪怕你自己排序 有什么问题 要求那么多

**Comment by LZX284** [comment]
> 那你fork自己改改呗

需要PR吗？

**Comment by TonyJiangWJ** [comment]
不需要 你自己玩你的
