### ISSUE TITLE
 console.setLogSize(14)出错 

### ISSUE THREAD

**Issue by lnxcyq** [TonyJiangWJ/Auto.js#19]
这个软件非常好，可以避免无障碍检测，但是这个也很多bug，一个普通的学习脚本都运行不下来，总提示出错，代码又没问题。

**Comment by CuteLicense** [comment]
不是bug吧，不同版本之间的不兼容而已

**Comment by lnxcyq** [comment]
发现一个bug，无法调用 console.setLogSize() 方法 (Edited)

**Comment by lnxcyq** [comment]
不是调别的API，是在本地脚本中写了 console.setLogSize(14)，运行时就出错。

**Comment by TonyJiangWJ** [comment]
无语 你自己看文档 有没有这个console.setLogSize的API http://docs.autojs.org/
