### ISSUE TITLE
困鱼currentPackage()、currentActivity()输出为空

### ISSUE THREAD

**Issue by hlyzhot** [TonyJiangWJ/Auto.js#2]
如题，尝试打开查看使用统计权限，然而应用列表找不到困鱼

**Comment by TonyJiangWJ** [comment]
这个功能导致无障碍耗电异常，所以我屏蔽掉了，只有后台运行着脚本的时候才能正确获取数据。你可以创建一个空的脚本挂着，比如：
```javascript
auto()
setInterval(() => {/*啥也不干*/}, 60000)
```

**Comment by hlyzhot** [comment]
> 这个功能导致无障碍耗电异常，所以我屏蔽掉了，只有后台运行着脚本的时候才能正确获取数据。你可以创建一个空的脚本挂着，比如：
> 
> ```js
> auto()
> setInterval(() => {/*啥也不干*/}, 60000)
> ```
这段代码不管在困鱼内还是别的app内运行输出都是空
```js auto();
console.show();
let i = 20;
while (i--) {
    sleep(1000);
    log(currentActivity());
    log(currentPackage());
}

setInterval(() => { /*啥也不干*/ }, 60000)

**Comment by TonyJiangWJ** [comment]
我的锅，再看了一眼 确实改错了那块代码

**Comment by TonyJiangWJ** [comment]
已修复版本：4.1.24.0417
