### ISSUE TITLE
大佬，反应两个问题

### ISSUE THREAD

**Issue by lnxcyq** [TonyJiangWJ/Auto.js#5]
一个是你这个也不支持paddle啊，怎么回事啊，我有脚本ocr，运行时提示“paddle”is not defined
第二，你这个“跳转”点击后没反应，我有一脚本很长，想跳转到某一行，实现不了

**Comment by TonyJiangWJ** [comment]
使用 $ocr 或者手动初始化predictor 具体见示例文件 你如果是别的地方过来的 建议使用他们的版本 而不是使用这个项目 本项目主要是针对我自己的脚本 如蚂蚁森林和蚂蚁庄园等 所以不太会去适应所有开发者 
第一我不是做安卓开发的所以能力有限，第二是我本人时间也不充裕 
另外在另一个issue也提到了，所有的优化都是为了能够运行稳定。
如果真拿来开发脚本的话 很多功能都是欠缺的，比如你提到的这个编辑器，比如脚本打包，比如USB连接VS插件等等
当然你们反馈的这些问题我也会尝试去修复，也欢迎提交PR 但是还是那句话 如果为了更丰富的功能 还是建议使用其他开源版本 比如AutoX
另外如果引用我这边的代码，请在类或者方法名的注释中注明原作者信息以及来源是本项目

**Comment by lnxcyq** [comment]
别生气。第一我英文都不认识几个，所以就不存在什么引用代码啦，我纯粹是拿来作工具运行我从别人那里弄来的脚本。第二，我是用过你的作品，现在为什么想继续用呢，因为我特别懒，别人的无障碍总是每次都要输入密码来开启，而你的不用，这一点很方便，只是可惜不能运行我的ocr脚本，就这么简单。不管怎么样，我都是向你致敬，因为我一向很崇敬有知识的年轻人，谢谢你。

**Comment by TonyJiangWJ** [comment]
那你按示例文件做一下修改吧 如果需要多个版本之间通用 那可能是比较麻烦
其他那些是说给所有能看到这条issue的人看的 不是针对你
