### ISSUE TITLE
Symbol 不能使用

### ISSUE THREAD

**Issue by sakur1204** [TonyJiangWJ/Auto.js#6]
let s1 = Symbol(1);
然后就报错了，Rhino 1.7.14 是应该是支持 Symbol 的

[autojs-log4j.txt](https://github.com/TonyJiangWJ/Auto.js/files/14722123/autojs-log4j.txt)

**Comment by TonyJiangWJ** [comment]
默认并不支持 需要加flag 需要使用请自己研究或者重新编译 用这玩意就别想着全兼容ES6了
