### ISSUE TITLE
clone 下来后 初次使用的时候报错 

### ISSUE THREAD

**Issue by xueyangkk** [TonyJiangWJ/Auto.js#7]
使用的autojs版本为 
https://github.com/SuperMonster003/AutoJs6

报错截图  
`错误: Error: Can't resolve relative module ID
"./modules/initJLneeded.js" when require()
is used outside of a module (file: " landroid
_asset/modules/jvm-npm.js#89)`

**Comment by xueyangkk** [comment]
这个错误原因找到  必须脚本传到手机上执行 就不会报错  但是现在又报了一个新的错误  


`
错误:TypeError: Expected argument of type object, but instead had type undefined (file:/storage/emulated/0/
脚本/workApp/AutoScriptBase/lib/ResourceMonitor.js#151)


`

**Comment by TonyJiangWJ** [comment]
你们发issue能不能发到对应仓库。。。
